### ISSUE TITLE
Queries hang when 20 threads concurrency query with TPCH 500

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#6554] opened 2022-12-28 05:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. tiup bench tpch --db tpch --host 10.2.12.58 --port 31599 run  --sf 500 --queries "q5,q13,q20" --threads 20
2. After 1 hour, all queries are hung and snapshots can't be released.

### 2. What did you expect to see? (Required)
Queries can be executed successfully.
### 3. What did you see instead (Required)
CPU usage dropped and it seems that there is no read tasks.
![image](https://user-images.githubusercontent.com/14118780/209763111-85cb7312-8de5-4479-a8ae-0c75674d2462.png)
![48d4f252-544c-4a2a-a4dd-084eafd2c9d4](https://user-images.githubusercontent.com/14118780/209762930-b175906a-4726-4b0e-b19d-c52e0050083b.jpeg)
![7718bd9f-d392-47d6-9a88-edb60f8e4b4c](https://user-images.githubusercontent.com/14118780/209762941-43f91514-ab06-4f70-84af-518de82085d5.jpeg)

**Comment by yibin87** [comment] 2023-01-03 07:49
From log file, some table scan operator hangs and doesn't finish with the finish message: "Finish read from storage". And thus the following operators and MPPTasks hang. Some of the storage log like this:
[2022/12/28 05:01:54.266 +00:00] [DEBUG] [DMVersionFilterBlockInputStream.h:80] ["Total rows: 899166, pass: 100.00%, complete pass: 100.00%, complete not pass: 0.00%,      not clean: 0.00%, is deleted: 0.00%, effective: 0.00%, read tso: 438358161730830420"] [source="mode=MVCC MPP<query:438358161730830420,task:38> table_id=189"] [thread_i     d=57]
3314 [2022/12/28 05:01:54.266 +00:00] [DEBUG] [ColumnSharingCache.h:137] ["dmfile /data0/db/data/t_189/stable/dmf_17903 stat add_count=0 add_stale=0 add_ratio=0 get_miss=74      get_part=0 get_hit=0 get_copy=0 cached_ratio=0"] [source="MPP<query:438358161730830420,task:38> table_id=189"] [thread_id=57]
3315 [2022/12/28 05:01:54.270 +00:00] [DEBUG] [Segment.cpp:1907] ["Begin segment getReadInfo"] [source="table_id=189 segment_id=9338 epoch=5 MPP<query:438358161730830420,ta     sk:38> table_id=189"] [thread_id=25]
3316 [2022/12/28 05:01:54.270 +00:00] [DEBUG] [Segment.cpp:1922] ["Finish segment getReadInfo"] [source="table_id=189 segment_id=9338 epoch=5 MPP<query:438358161730830420,t     ask:38> table_id=189"] [thread_id=25]
3317 [2022/12/28 05:01:54.270 +00:00] [DEBUG] [StableValueSpace.cpp:351] ["max_data_version: 438358161730830420, enable_handle_clean_read: true, is_fast_mode: false, enable     _del_clean_read: false"] [source="table_id=189 segment_id=9338 epoch=5"] [thread_id=25]
3318 [2022/12/28 05:01:54.270 +00:00] [DEBUG] [DMFilePackFilter.h:224] ["RSFilter exclude rate: 0.00, after_pk: 116, after_read_packs: 116, after_filter: 116, handle_ranges     : {[03800000007A4F0142038000000000000004,03800000007A5448E6038000000000000001),[03800000007A560CC3038000000000000003,03800000007A5718C0038000000000000006),[03800000007     A5F32E6038000000000000001,03800000007A674B25038000000000000004)}, read_packs: 0, pack_count: 116"] [source="MPP<query:438358161730830420,task:38> table_id=189"] [threa     d_id=25]
3319 [2022/12/28 05:01:54.270 +00:00] [DEBUG] [SegmentReadTaskPool.cpp:161] ["getInputStream succ, pool_id=106532 segment_id=9338"] [source="MPP<query:438358161730830420,ta     sk:38> table_id=189"] [thread_id=25]
3320 [2022/12/28 05:01:57.696 +00:00] [DEBUG] [SegmentReadTaskPool.cpp:174] ["finishSegment pool_id=106532 segment_id=9494 pool_finished=false"] [source="MPP<query:43835816     1730830420,task:38> table_id=189"] [thread_id=39]
3321 [2022/12/28 05:01:57.696 +00:00] [DEBUG] [DMVersionFilterBlockInputStream.h:80] ["Total rows: 231106, pass: 100.00%, complete pass: 100.00%, complete not pass: 0.00%,      not clean: 0.00%, is deleted: 0.00%, effective: 0.00%, read tso: 438358161730830420"] [source="mode=MVCC MPP<query:438358161730830420,task:38> table_id=189"] [thread_i     d=39]
3322 [2022/12/28 05:01:57.696 +00:00] [DEBUG] [ColumnSharingCache.h:137] ["dmfile /data0/db/data/t_189/stable/dmf_642972 stat add_count=0 add_stale=0 add_ratio=0 get_miss=2     3 get_part=0 get_hit=0 get_copy=0 cached_ratio=0"] [source="MPP<query:438358161730830420,task:38> table_id=189"] [thread_id=39]
3323 [2022/12/28 05:01:57.696 +00:00] [DEBUG] [SegmentReadTaskPool.cpp:174] ["finishSegment pool_id=106532 segment_id=9482 pool_finished=false"] [source="MPP<query:43835816     1730830420,task:38> table_id=189"] [thread_id=65]
3324 [2022/12/28 05:01:57.696 +00:00] [DEBUG] [DMVersionFilterBlockInputStream.h:80] ["Total rows: 184266, pass: 100.00%, complete pass: 100.00%, complete not pass: 0.00%,      not clean: 0.00%, is deleted: 0.00%, effective: 0.00%, read tso: 438358161730830420"] [source="mode=MVCC MPP<query:438358161730830420,task:38> table_id=189"] [thread_i     d=65]
3325 [2022/12/28 05:01:57.696 +00:00] [DEBUG] [ColumnSharingCache.h:137] ["dmfile /data0/db/data/t_189/stable/dmf_563990 stat add_count=0 add_stale=0 add_ratio=0 get_miss=3     3 get_part=0 get_hit=0 get_copy=0 cached_ratio=0"] [source="MPP<query:438358161730830420,task:38> table_id=189"] [thread_id=65]
3326 [2022/12/28 05:01:57.697 +00:00] [DEBUG] [Segment.cpp:1907] ["Begin segment getReadInfo"] [source="table_id=189 segment_id=9302 epoch=6 MPP<query:438358161730830420,ta     sk:38> table_id=189"] [thread_id=65]

**Comment by yibin87** [comment] 2023-01-03 08:12
No remote read, since no "Start to build remote request" log found.

**Comment by yibin87** [comment] 2023-01-04 01:23
BTW, the exception post in this issue doesn't have anything with the hang. Because the hang is caused from 13:00, while the exception is 12:49.

**Comment by hehechen** [comment] 2023-01-04 05:13
> BTW, the exception post in this issue doesn't have anything with the hang. Because the hang happened after 13:00, while the exception happened at 12:49.

There have been two hangs, the exception post  in this issue is the first one.

**Comment by yibin87** [comment] 2023-01-05 03:08
> > BTW, the exception post in this issue doesn't have anything with the hang. Because the hang happened after 13:00, while the exception happened at 12:49.
> 
> There have been two hangs, the exception post in this issue is the first one.

Yes, I think the exception is caused by tidb final cancel requests probably. From following test, during the hang, there're no exceptions thrown or any error messages.

**Comment by hehechen** [comment] 2023-01-05 06:35
> > > BTW, the exception post in this issue doesn't have anything with the hang. Because the hang happened after 13:00, while the exception happened at 12:49.
> > 
> > 
> > There have been two hangs, the exception post in this issue is the first one.
> 
> Yes, I think the exception is caused by tidb final cancel requests probably. From following test, during the hang, there're no exceptions thrown or any error messages.

Yes, after this exception, snapshots are released.

**Comment by yibin87** [comment] 2023-01-13 06:39
Close the issue, because not reproducable now. Please reopen it when it happen again.

**Comment by yibin87** [comment] 2023-02-03 02:14
The cluster doesn't hang, but execute really slow due to slow shuffle. And the issue can reproduce in one day with 40-tiflash nodes.
Locating the real issue by configure the "async server" and "async client" values now.

**Comment by zanmato1984** [comment] 2024-05-08 08:48
It's probably gone after we introduced pipeline model. Removing affects-7.5+ labels and closing.

**Closed by zanmato1984** 2024-05-08 08:48 UTC
Labels: type/bug, severity/major, may-affects-4.0, may-affects-5.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, component/compute, may-affects-6.1, may-affects-6.5, affects-7.0, affects-7.1
