### ISSUE TITLE
There are some crash info about grpc

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#6019] opened 2022-09-23 23:37 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022/09/23 22:48:23.186 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=43049]
[2022/09/23 22:48:23.186 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 28244) Received signal Aborted(6)."] [thread_id=43049]
[2022/09/23 22:48:23.405 +08:00] [ERROR] [BaseDaemon.cpp:570] ["BaseDaemon:
       0x65efa41    faultSignalHandler(int, siginfo_t*, void*) [tiflash+106887745]
                    libs/libdaemon/src/BaseDaemon.cpp:221
  0x7f5c12495630    <unknown symbol> [libpthread.so.0+63024]
  0x7f5c117ca387    gsignal [libc.so.6+222087]
  0x7f5c117cba78    __GI_abort [libc.so.6+227960]
       0x7e510ce    gpr_malloc [tiflash+132452558]
                    contrib/grpc/src/core/lib/gpr/alloc.cc:35
       0x7b40bbc    grpc_slice_malloc [tiflash+129239996]
                    contrib/grpc/src/core/lib/slice/slice.cc:323
       0x7963e71    grpc::CoreCodegen::grpc_slice_malloc(unsigned long) [tiflash+127286897]
                    contrib/grpc/src/cpp/common/core_codegen.cc:174
       0x707c74e    grpc::ProtoBufferWriter::Next(void**, int*) [tiflash+117950286]
                    contrib/grpc/include/grpcpp/impl/codegen/proto_buffer_writer.h:104
       0x799ec80    google::protobuf::io::EpsCopyOutputStream::WriteRawFallback(void const*, int, unsigned char*) [tiflash+127528064]
                    contrib/protobuf/src/google/protobuf/io/coded_stream.cc:844
       0x776e0ad    coprocessor::Response::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const [tiflash+125231277]
                    build/contrib/kvproto/cpp/kvproto/coprocessor.pb.cc:1310
       0x79a1c07    google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const [tiflash+127540231]
                    contrib/protobuf/src/google/protobuf/message_lite.cc:412
       0x777f74c    grpc::Status grpc::GenericSerialize<grpc::ProtoBufferWriter, google::protobuf::MessageLite>(google::protobuf::MessageLite const&, grpc::ByteBuffer*, bool*) [tiflash+125302604]
                    contrib/grpc/include/grpcpp/impl/codegen/proto_utils.h:66
       0x777f5ac    std::__1::__function::__func<grpc::Status grpc::internal::CallOpSendMessage::SendMessagePtr<google::protobuf::MessageLite>(google::protobuf::MessageLite const*, grpc::WriteOptions)::'lambda'(void const*), std::__1::allocator<grpc::Status grpc::internal::CallOpSendMessage::SendMessagePtr<google::protobuf::MessageLite>(google::protobuf::MessageLite const*, grpc::WriteOptions)::'lambda'(void const*)>, grpc::Status (void const*)>::operator()(void const*&&) [tiflash+125302188]
                    /data1/jaysonhuang/tiflash-env/sysroot/bin/../include/c++/v1/__functional/function.h:345
       0x707bc45    grpc::internal::CallOpSendMessage::AddOp(grpc_op*, unsigned long*) [tiflash+117947461]
                    contrib/grpc/include/grpcpp/impl/codegen/call_op_set.h:317
       0x707b878    grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpServerSendStatus, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::ContinueFillOpsAfterInterception() [tiflash+117946488]
                    contrib/grpc/include/grpcpp/impl/codegen/call_op_set.h:965
       0x7784f3b    void grpc::internal::UnaryRunHandlerHelper<google::protobuf::MessageLite>(grpc::internal::MethodHandler::HandlerParameter const&, google::protobuf::MessageLite*, grpc::Status&) [tiflash+125325115]
                    contrib/grpc/include/grpcpp/impl/codegen/method_handler.h:75
       0x794705c    grpc::internal::RpcMethodHandler<tikvpb::Tikv::Service, coprocessor::Request, coprocessor::Response, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) [tiflash+127168604]
                    contrib/grpc/include/grpcpp/impl/codegen/method_handler.h:120
       0x796f859    grpc::Server::SyncRequest::ContinueRunAfterInterception() [tiflash+127334489]
                    contrib/grpc/src/cpp/server/server_cc.cc:433
       0x796f668    grpc::Server::SyncRequest::Run(std::__1::shared_ptr<grpc::Server::GlobalCallbacks> const&, bool) [tiflash+127333992]
                    contrib/grpc/src/cpp/server/server_cc.cc:421
       0x797f207    grpc::ThreadManager::MainWorkLoop() [tiflash+127398407]
                    contrib/grpc/src/cpp/thread_manager/thread_manager.cc:211
       0x797fad1    grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::$_0::__invoke(void*) [tiflash+127400657]
                    contrib/grpc/src/cpp/thread_manager/thread_manager.cc:36
       0x7e57d8c    grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) [tiflash+132480396]
                    contrib/grpc/src/core/lib/gprpp/thd_posix.cc:110
  0x7f5c1248dea5    start_thread [libpthread.so.0+32421]"] [thread_id=43049]
```
### 4. What is your TiFlash version? (Required)
master

**Comment by JaySon-Huang** [comment] 2022-09-29 15:04
```
[2022/09/29 01:04:05.498 +08:00] [ERROR] [BaseDaemon.cpp:570] [\"BaseDaemon:
       0x56bdc01    faultSignalHandler(int, siginfo_t*, void*) [tiflash+90954753]
                    libs/libdaemon/src/BaseDaemon.cpp:221
  0x7f44cc17a630    <unknown symbol> [libpthread.so.0+63024]
  0x7f44cb4af387    gsignal [libc.so.6+222087]
  0x7f44cb4b0a78    __GI_abort [libc.so.6+227960]
       0x6160e9b    grpc::ProtoBufferWriter::Next(void**, int*) [tiflash+102108827]
                    contrib/grpc/include/grpcpp/impl/codegen/proto_buffer_writer.h:104
       0x68df650    google::protobuf::io::EpsCopyOutputStream::WriteRawFallback(void const*, int, unsigned char*) [tiflash+109966928]
                    contrib/protobuf/src/google/protobuf/io/coded_stream.cc:844
       0x6670807    coprocessor::Response::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const [tiflash+107415559]
                    release-centos7-llvm/build-release/contrib/kvproto/cpp/kvproto/coprocessor.pb.cc:1310
       0x68e212d    google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const [tiflash+109977901]
                    contrib/protobuf/src/google/protobuf/message_lite.cc:412
       0x667edf8    grpc::Status grpc::GenericSerialize<grpc::ProtoBufferWriter, google::protobuf::MessageLite>(google::protobuf::MessageLite const&, grpc::ByteBuffer*, bool*) [tiflash+107474424]
                    contrib/grpc/include/grpcpp/impl/codegen/proto_utils.h:66
       0x667ebac    std::__1::__function::__func<grpc::Status grpc::internal::CallOpSendMessage::SendMessagePtr<google::protobuf::MessageLite>(google::protobuf::MessageLite const*, grpc::WriteOptions)::'lambda'(void const*), std::__1::allocator<grpc::Status grpc::internal::CallOpSendMessage::SendMessagePtr<google::protobuf::MessageLite>(google::protobuf::MessageLite const*, grpc::WriteOptions)::'lambda'(void const*)>, grpc::Status (void const*)>::operator()(void const*&&) [tiflash+107473836]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:345
       0x6160345    grpc::internal::CallOpSendMessage::AddOp(grpc_op*, unsigned long*) [tiflash+102105925]
                    contrib/grpc/include/grpcpp/impl/codegen/call_op_set.h:317
       0x615ff27    grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal::CallOpSendMessage, grpc::internal::CallOpServerSendStatus, grpc::internal::CallNoOp<4>, grpc::internal::CallNoOp<5>, grpc::internal::CallNoOp<6> >::ContinueFillOpsAfterInterception() [tiflash+102104871]
                    contrib/grpc/include/grpcpp/impl/codegen/call_op_set.h:965
       0x66844d8    void grpc::internal::UnaryRunHandlerHelper<google::protobuf::MessageLite>(grpc::internal::MethodHandler::HandlerParameter const&, google::protobuf::MessageLite*, grpc::Status&) [tiflash+107496664]
                    contrib/grpc/include/grpcpp/impl/codegen/method_handler.h:75
       0x687f320    grpc::internal::RpcMethodHandler<tikvpb::Tikv::Service, coprocessor::Request, coprocessor::Response, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) [tiflash+109572896]
                    contrib/grpc/include/grpcpp/impl/codegen/method_handler.h:120
       0x68c0860    grpc::Server::SyncRequest::ContinueRunAfterInterception() [tiflash+109840480]
                    contrib/grpc/src/cpp/server/server_cc.cc:433
       0x68c0691    grpc::Server::SyncRequest::Run(std::__1::shared_ptr<grpc::Server::GlobalCallbacks> const&, bool) [tiflash+109840017]
                    contrib/grpc/src/cpp/server/server_cc.cc:421
       0x68d2885    grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::$_0::__invoke(void*) [tiflash+109914245]
                    contrib/grpc/src/cpp/thread_manager/thread_manager.cc:36
       0x6bf4f9a    grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) [tiflash+113201050]
                    contrib/grpc/src/core/lib/gprpp/thd_posix.cc:110
  0x7f44cc172ea5    start_thread [libpthread.so.0+32421]\"] [thread_id=36494]"}
```
Seems it happen when OOM happens
```
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906209133+08:00 stdout F [2022/09/29 01:04:07.128 +08:00] [ERROR] [MPPTask.cpp:430] [\"MPPTask:MPP<query:436308396189941819,task:8> task running meets error: Code: 0, e.displayText() = DB::Exception: std::bad_alloc, e.what() = DB::Exception, Stack trace:\\n\\n\\n       0x5f1d0fd\\tDB::DM::SegmentReader::run() [tiflash+99733757]\\n                \\tdbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp:152\\n       0x5f1d742\\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*> >(void*) [tiflash+99735362]\\n                \\t/usr/local/bin/../include/c++/v1/thread:291\\n  0x7f44cc172ea5\\tstart_thread [libpthread.so.0+32421]\\n  0x7f44cb57796d\\t__clone [libc.so.6+1042797]\"] [thread_id=2025]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906195983+08:00 stdout F [2022/09/29 01:04:07.127 +08:00] [ERROR] [SegmentReader.cpp:130] [\"SegmentReader:ErrMsg: std::bad_alloc\"] [thread_id=22]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906189006+08:00 stdout F [2022/09/29 01:04:07.124 +08:00] [ERROR] [Server.cpp:314] [\"grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/cpp/thread_manager/thread_manager.cc, line number: 39, log msg : Could not create grpc_sync_server worker-thread\"] [thread_id=23987]"}


  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906146683+08:00 stdout F [2022/09/29 01:04:07.124 +08:00] [ERROR] [BaseDaemon.cpp:378] [\"BaseDaemon:(from thread 26304) Received signal Aborted(6).\"] [thread_id=36494]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906140356+08:00 stdout F [2022/09/29 01:04:07.124 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=36494]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906133406+08:00 stdout F [2022/09/29 01:04:07.122 +08:00] [ERROR] [Server.cpp:314] [\"grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/cpp/thread_manager/thread_manager.cc, line number: 39, log msg : Could not create grpc_sync_server worker-thread\"] [thread_id=23987]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906118049+08:00 stdout F [2022/09/29 01:04:07.120 +08:00] [ERROR] [<unknown>] [\"pingcap.tikv: Failed8: Server Threadpool Exhausted\"] [thread_id=21131]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906099703+08:00 stdout F [2022/09/29 01:04:07.119 +08:00] [ERROR] [Server.cpp:314] [\"grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/cpp/thread_manager/thread_manager.cc, line number: 39, log msg : Could not create grpc_sync_server worker-thread\"] [thread_id=23987]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906085026+08:00 stdout F [2022/09/29 01:04:07.118 +08:00] [ERROR] [<unknown>] [\"pingcap.tikv: Failed8: Server Threadpool Exhausted\"] [thread_id=12200]"}
  |   | 2022-09-29 01:04:07 | {"container":"errorlog","namespace":"endless-htap-currency-partition-tps-1262948-1-565","pod":"tc-tiflash-1","log":"2022-09-29T01:04:07.906077921+08:00 stdout F [2022/09/29 01:04:07.118 +08:00] [ERROR] [Server.cpp:314] [\"grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/cpp/thread_manager/thread_manager.cc, line number: 39, log msg : Could not create grpc_sync_server worker-thread\"] [thread_id=23987]"}


```

**Comment by flowbehappy** [comment] 2023-02-14 05:43
Change severity to minor and close it, since it is likely caused by OOM.

**Closed by flowbehappy** 2023-02-14 05:43 UTC
Labels: type/bug, severity/minor, may-affects-4.0, may-affects-5.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-6.0, component/storage, may-affects-6.1, may-affects-6.2, may-affects-6.3, affects-6.4, affects-6.5, affects-6.6

**Comment by MimeLyc** [comment] 2023-06-12 02:30
update
