### ISSUE TITLE
Enhance the query performance in Fast Mode

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#5455] opened 2022-07-25 02:31 UTC
## Enhancement

For some complex queries, the query performance in the fast mode is worse than in the normal mode. Thus we need to enhance the performance in these queries, to make the performance in the fast mode is always better than in the normal mode.

**Comment by flowbehappy** [comment] 2022-07-27 05:09
Looks like we cannot reproduce the issue, can we close it? @hongyunyan

**Closed** 2022-07-27 05:12 UTC
Labels: type/enhancement, severity/major, component/storage, affects-6.2
