### ISSUE TITLE
Abnormal metrics reported by tiflash-proxy

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#6347] opened 2022-11-22 06:41 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deploy a v6.4.0 cluster and run high pressure update workloads.

### 3. What did you see instead (Required)
The CPU and memory reported by tiflash-proxy is abnormal. However, the metrics reported by tiflash is OK
![image](https://user-images.githubusercontent.com/4865550/203213617-104f649b-8015-4db2-9fb2-63523ef58277.png)
![image](https://user-images.githubusercontent.com/4865550/203242992-ef6bd756-814b-44c1-a16c-b16293dc0d52.png)

### 4. What is your TiFlash version? (Required)
v6.4.0

**Comment by hehechen** [comment] 2022-11-23 03:18
This is because the profile takes more time than expected, causing the `status_server` thread to be stuck and unable to process the http request of prometheus.
For example: A 10s profile takes more than a minute 
![image](https://user-images.githubusercontent.com/14118780/203462821-9d49ef4f-07ea-4d0e-b826-343d06779ed3.png)

The reason why profile took longer than expected is still under investigation.

**Comment by hehechen** [comment] 2022-11-28 02:23
It seems that the overhead of `dwarf` is larger than that of `frame pointer.` I tried to revert this [PR](https://github.com/pingcap/tidb-engine-ext/pull/193) and it will be fine.

**Comment by hehechen** [comment] 2022-11-29 05:49
I add some logs in https://github.com/rust-lang/backtrace-rs/blob/a59e64f50c571d9675616321b22c2953d70d1a8b/src/symbolize/gimli.rs#L338, and found out that the number of `dwarf` symbols is much more than `frame pointer`.
`dwarf`:
![image](https://user-images.githubusercontent.com/14118780/204448821-a0cc32b9-1675-4520-aa3a-cd49c383f939.png)
`frame pointer`:
![image](https://user-images.githubusercontent.com/14118780/204448886-88808c38-b351-4d28-8938-8fa2c6aa638c.png)
So the overhead of `dwarf` resolving symbol  is larger than that of  `frame pointer`.

**Closed** 2022-11-29 07:10 UTC
Labels: type/bug, severity/minor, component/storage, affects-6.4

**Comment by hehechen** [comment] 2022-12-01 01:53
The root cause is that the backtrace of DWARF is deeper than that of `frame pointer`. So DWARF need to resolve more shared libraries when resolving symbols. But [the capacity of lib cache in backtrace-rs is only 4](https://github.com/rust-lang/backtrace-rs/blob/5be2e8ba9cf6e391c5fa45219fc091b4075eb6be/src/symbolize/gimli.rs#L55), so cache miss will occurs frequently in DWARF.
After I increased [the capacity of lib cache in backtrace-rs ] (https://github.com/rust-lang/backtrace-rs/blob/5be2e8ba9cf6e391c5fa45219fc091b4075eb6be/src/symbolize/gimli.rs#L55) to 10, the 10 seconds profile took less than 11 seconds, and the metrics became normal.

one backtrace comparison:
frame pointer:
![image](https://user-images.githubusercontent.com/14118780/204844116-9da45d67-443c-49c5-8428-0326487dde00.png)
DWARF:
![image](https://user-images.githubusercontent.com/14118780/204844208-a9927a7f-1e11-41eb-a743-71a0ced93ef6.png)

Some libraries when DWARF need to resolve:
![image](https://user-images.githubusercontent.com/14118780/204947012-fad9307c-e6ba-4629-896c-ab60ca7fd14a.png)
