### ISSUE TITLE
TiFlash crash randomly after cluster restart when TLS is enabled

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tiflash#4196] opened 2022-03-08 07:18 UTC
## Bug Report

Looks very like: https://github.com/grpc/grpc/issues/23144

### 1. Minimal reproduce step (Required)
1. start a cluster of v5.4.0 and **enable TLS**, there should be multiple tiflash nodes(the more the better)
2. load tpch100/20
3. run query like `select count(*) from (select count(*) from lineitem group by l_orderkey, l_suppkey)d;`
4. restart cluster

repeat step 3 and step 4 multiple time, TiFlash will crash

### 2. What did you expect to see? (Required)
run normally
### 3. What did you see instead (Required)
 TiFlash will crash
### 4. What is your TiFlash version? (Required)
v5.4.0

**Comment by zanmato1984** [comment] 2022-04-11 07:19
Thanks for the great work of @s3nt3, the root cause has been confirmed to be the openssl error stack issue.

Grpc has fixed this issue in https://github.com/grpc/grpc/pull/26834, v1.41.0.

**Comment by VelocityLight** [comment] 2022-04-12 07:04
update

**Comment by zanmato1984** [comment] 2022-04-21 06:55
update

**Comment by zanmato1984** [comment] 2022-05-11 04:27
All PR merged to affected branches. Closing.

**Closed by zanmato1984** 2022-05-11 04:27 UTC
Labels: type/bug, severity/critical, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, may-affects-4.0, component/compute
