### ISSUE TITLE
Copy rough set index Data in a wrong way

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tiflash#8301] opened 2023-11-02 11:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tiflash/blob/ec00c9ae143b5b8ef7582972e5fee5eb5a4fbf39/dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp#L307-L311

When using String, we should use reinterpret_cast<const char *>(&chars[prev_offset]) instead of chars[prev_offset], so that it will call constructor `constexpr basic_string( const CharT* s, const Allocator& alloc = Allocator())` rather than `constexpr basic_string( size_type count, CharT ch, const Allocator& alloc = Allocator() );`

**Comment by JaySon-Huang** [comment] 2023-11-03 03:38
the issue is fixed in the master branch by https://github.com/pingcap/tiflash/pull/8298

**Closed by JaySon-Huang** 2023-11-03 03:38 UTC
Labels: type/bug, severity/minor, component/storage, affects-6.1, affects-6.5, affects-7.1, affects-7.5
