### ISSUE TITLE
TiFlash crash when open tls

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#5953] opened 2022-09-19 12:40 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

open tls
```
[2022/09/19 19:17:06.648 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=120]
[2022/09/19 19:17:06.648 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 119) Received signal Segmentation fault(11)."] [thread_id=120]
[2022/09/19 19:17:06.649 +08:00] [ERROR] [BaseDaemon.cpp:406] ["BaseDaemon:Address: NULL pointer."] [thread_id=120]
[2022/09/19 19:17:06.649 +08:00] [ERROR] [BaseDaemon.cpp:414] ["BaseDaemon:Access: read."] [thread_id=120]
[2022/09/19 19:17:06.649 +08:00] [ERROR] [BaseDaemon.cpp:426] ["BaseDaemon:Unknown si_code."] [thread_id=120]
[2022/09/19 19:17:06.650 +08:00] [ERROR] [Server.cpp:314] ["grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/core/tsi/ssl_transport_security.cc, line number: 1688, log msg : Unexpected error received from first SSL_do_handshake call: SSL_ERROR_SSL"] [thread_id=121]
[2022/09/19 19:17:06.650 +08:00] [ERROR] [Server.cpp:314] ["grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/core/lib/security/security_connector/ssl/ssl_security_connector.cc, line number: 133, log msg : Handshaker creation failed with error TSI_INTERNAL_ERROR."] [thread_id=121]
[2022/09/19 19:17:06.661 +08:00] [ERROR] [Server.cpp:314] ["grpc:/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/grpc/src/core/tsi/ssl_transport_security.cc, line number: 1504, log msg : Handshake failed with fatal error SSL_ERROR_SSL: error:0407E086:rsa routines:RSA_verify_PKCS1_PSS_mgf1:last octet invalid."] [thread_id=124]
[2022/09/19 19:17:06.665 +08:00] [WARN] [ExchangeReceiver.cpp:252] ["ExchangeReceiver:MPP<query:436099147788451845,task:13> ExchangeReceiver_62 tunnel8+13 MakeReader fail. retry time: 0"] [thread_id=125]
[2022/09/19 19:17:06.669 +08:00] [WARN] [ExchangeReceiver.cpp:252] ["ExchangeReceiver:MPP<query:436099147788451845,task:7> ExchangeReceiver_60 tunnel5+7 MakeReader fail. retry time: 0"] [thread_id=129]
[2022/09/19 19:17:06.793 +08:00] [WARN] [ExchangeReceiver.cpp:252] ["ExchangeReceiver:MPP<query:436099147804966914,task:8> ExchangeReceiver_61 tunnel1+8 MakeReader fail. retry time: 0"] [thread_id=147]
[2022/09/19 19:17:06.811 +08:00] [WARN] [ExchangeReceiver.cpp:252] ["ExchangeReceiver:MPP<query:436099147804966914,task:5> ExchangeReceiver_66 tunnel3+5 MakeReader fail. retry time: 0"] [thread_id=155]
[2022/09/19 19:17:06.887 +08:00] [ERROR] [BaseDaemon.cpp:570] ["BaseDaemon:\n       0x6718131\tfaultSignalHandler(int, siginfo_t*, void*) [tiflash+108101937]\n                \tlibs/libdaemon/src/BaseDaemon.cpp:221\n  0x7f8649222630\t<unknown symbol> [libpthread.so.0+63024]\n       0x79b3770\tgrpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange() [tiflash+127612784]\n                \tcontrib/grpc/src/core/ext/filters/client_channel/client_channel.cc:581\n       0x79d2ea1\tgrpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_connectivity_state, absl::lts_20211102::Status const&)::'lambda'(void*, grpc_error*)::__invoke(void*, grpc_error*) [tiflash+127741601]\n                \tcontrib/grpc/src/core/ext/filters/client_channel/subchannel.cc:363\n       0x7a2e901\tpollset_work(grpc_pollset*, grpc_pollset_worker**, long) [tiflash+128116993]\n                \tcontrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1139\n       0x7aad60e\tcq_next(grpc_completion_queue*, gpr_timespec, void*) [tiflash+128636430]\n                \tcontrib/grpc/src/core/lib/surface/completion_queue.cc:1047\n       0x726ec44\tDB::GRPCCompletionQueuePool::thread(unsigned long) [tiflash+119991364]\n                \tdbms/src/Flash/Mpp/GRPCCompletionQueuePool.cpp:58\n       0x726f5b2\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::GRPCCompletionQueuePool::*)(unsigned long), DB::GRPCCompletionQueuePool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::GRPCCompletionQueuePool::*&&)(unsigned long), DB::GRPCCompletionQueuePool*&&, unsigned long&)::'lambda'(auto&&...), DB::GRPCCompletionQueuePool*, unsigned long> >(void*) [tiflash+119993778]\n                \t/usr/local/bin/../include/c++/v1/thread:291\n  0x7f864921aea5\tstart_thread [libpthread.so.0+32421]\n                \t/usr/src/debug/glibc-2.17-c758a686/nptl/pthread_create.c:307"] [thread_id=120]
[2022/09/19 19:17:06.887 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=120]
[2022/09/19 19:17:06.887 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 154) Received signal Segmentation fault(11)."] [thread_id=120]
[2022/09/19 19:17:06.887 +08:00] [ERROR] [BaseDaemon.cpp:406] ["BaseDaemon:Address: NULL pointer."] [thread_id=120]
[2022/09/19 19:17:06.887 +08:00] [ERROR] [BaseDaemon.cpp:414] ["BaseDaemon:Access: read."] [thread_id=120]
[2022/09/19 19:17:06.887 +08:00] [ERROR] [BaseDaemon.cpp:426] ["BaseDaemon:Unknown si_code."] [thread_id=120]
[2022/09/19 19:17:06.890 +08:00] [ERROR] [BaseDaemon.cpp:570] ["BaseDaemon:\n       0x6718131\tfaultSignalHandler(int, siginfo_t*, void*) [tiflash+108101937]\n                \tlibs/libdaemon/src/BaseDaemon.cpp:221\n  0x7f8649222630\t<unknown symbol> [libpthread.so.0+63024]\n       0x79b3770\tgrpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange() [tiflash+127612784]\n                \tcontrib/grpc/src/core/ext/filters/client_channel/client_channel.cc:581\n       0x79d2ea1\tgrpc_core::Subchannel::AsyncWatcherNotifierLocked::AsyncWatcherNotifierLocked(grpc_core::RefCountedPtr<grpc_core::Subchannel::ConnectivityStateWatcherInterface>, grpc_connectivity_state, absl::lts_20211102::Status const&)::'lambda'(void*, grpc_error*)::__invoke(void*, grpc_error*) [tiflash+127741601]\n                \tcontrib/grpc/src/core/ext/filters/client_channel/subchannel.cc:363\n       0x7a2e901\tpollset_work(grpc_pollset*, grpc_pollset_worker**, long) [tiflash+128116993]\n                \tcontrib/grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1139\n       0x7aad60e\tcq_next(grpc_completion_queue*, gpr_timespec, void*) [tiflash+128636430]\n                \tcontrib/grpc/src/core/lib/surface/completion_queue.cc:1047\n       0x726ec44\tDB::GRPCCompletionQueuePool::thread(unsigned long) [tiflash+119991364]\n                \tdbms/src/Flash/Mpp/GRPCCompletionQueuePool.cpp:58\n       0x726f5b2\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::GRPCCompletionQueuePool::*)(unsigned long), DB::GRPCCompletionQueuePool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::GRPCCompletionQueuePool::*&&)(unsigned long), DB::GRPCCompletionQueuePool*&&, unsigned long&)::'lambda'(auto&&...), DB::GRPCCompletionQueuePool*, unsigned long> >(void*) [tiflash+119993778]\n                \t/usr/local/bin/../include/c++/v1/thread:291\n  0x7f864921aea5\tstart_thread [libpthread.so.0+32421]\n                \t/usr/src/debug/glibc-2.17-c758a686/nptl/pthread_create.c:307"] [thread_id=120]
```
### 4. What is your TiFlash version? (Required)
master 3124b24e3dea2b9783ba15c99ad1539ba6aae9a2

**Comment by lidezhu** [comment] 2022-09-22 07:24
The build image of tiflash have upgraded from `1.1.1l` to `1.1.1o`. And the problem doesn't occurs any more. So just close this issue and can open it if the problem still happens.

**Comment by lidezhu** [comment] 2022-09-22 08:56
The problem still occurs, so reopen this issue.

**Comment by bestwoody** [comment] 2022-10-09 08:25
it seems caused by unsynced system clock。

**Comment by lidezhu** [comment] 2022-10-27 06:25
Fixed in #6126

**Closed by lidezhu** 2022-10-27 06:25 UTC
Labels: type/bug, severity/critical, feature/developing, component/storage
