### ISSUE TITLE
TiFlash with s3 raise Exception: Key is locked

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#7304] opened 2023-04-18 02:44 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

ch workload and deploy tiflash with s3 using minio
### 3. What did you see instead (Required)
query failed for ```Error 1105: other error for mpp stream: From MPP<query:<query_ts:1681742959048667887, local_query_id:839, server_id:2259244, start_ts:440858826251960386>,task_id:2>: Poco::Exception. Code: 1000, e.code() = 10018, e.displayText() = Exception: Key is locked (1 locks in region {8271}), e.what() = Exception```
### 4. What is your TiFlash version? (Required)
master

**Comment by JaySon-Huang** [comment] 2023-04-18 08:15
Seems that syncing data from tikv is too slow, though the read node try resolve lock. But after lock resolved success, tiflash still meet the same locks for a long time.

For example, 2 locks from Region 8271, 8289 happens first at 14:49:19, and a RN resolve lock success. But next time RN retry for those region, it still meet the same lock from Region 8271, 8289. Only after 14:49:39, the lock from Region 8289 is resolved but the another lock from Region 8271 still not resolved.

And the query finally get timeouts for resolving locks around 14:49:39, error is returned to tidb.

[0418-ch-logs.tar.gz](https://github.com/pingcap/tiflash/files/11259375/0418-ch-logs.tar.gz)
```
440858826251960386.wn-0.log:[2023/04/17 14:49:19.077 +00:00] [DEBUG] [FlashService.cpp:716] ["Handle EstablishDisaggTask request done, resp_err=error_locked { msg: \"Key is locked (2 locks in region {8271, 8289})\" locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005\\236\\024x\" lock_ttl: 20043 txn_size: 62 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005w\\347\\016\" lock_ttl: 20043 txn_size: 9 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } }"] [source="DisTaskId<MPP<query:<query_ts:1681742959048667887, local_query_id:839, server_id:2259244, start_ts:440858826251960386>,task_id:2>,executor=TableFullScan_28>"] [thread_id=721]
... repeated for 42 times ...
440858826251960386.wn-0.log:[2023/04/17 14:49:38.804 +00:00] [DEBUG] [FlashService.cpp:716] ["Handle EstablishDisaggTask request done, resp_err=error_locked { msg: \"Key is locked (2 locks in region {8271, 8289})\" locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005\\236\\024x\" lock_ttl: 20043 txn_size: 62 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005w\\347\\r\" lock_ttl: 20043 txn_size: 9 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } }"] [source="DisTaskId<MPP<query:<query_ts:1681742959048667887, local_query_id:839, server_id:2259244, start_ts:440858826251960386>,task_id:2>,executor=TableFullScan_28>"] [thread_id=336]

440858826251960386.wn-0.log:[2023/04/17 14:49:39.336 +00:00] [DEBUG] [FlashService.cpp:716] ["Handle EstablishDisaggTask request done, resp_err=error_locked { msg: \"Key is locked (1 locks in region {8271})\" locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005w\\347\\r\" lock_ttl: 20043 txn_size: 9 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } }"] [source="DisTaskId<MPP<query:<query_ts:1681742959048667887, local_query_id:839, server_id:2259244, start_ts:440858826251960386>,task_id:2>,executor=TableFullScan_28>"] [thread_id=227]
440858826251960386.wn-0.log:[2023/04/17 14:49:39.868 +00:00] [DEBUG] [FlashService.cpp:716] ["Handle EstablishDisaggTask request done, resp_err=error_locked { msg: \"Key is locked (1 locks in region {8271})\" locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005w\\347\\r\" lock_ttl: 20043 txn_size: 9 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } }"] [source="DisTaskId<MPP<query:<query_ts:1681742959048667887, local_query_id:839, server_id:2259244, start_ts:440858826251960386>,task_id:2>,executor=TableFullScan_28>"] [thread_id=186]
440858826251960386.wn-0.log:[2023/04/17 14:49:40.400 +00:00] [DEBUG] [FlashService.cpp:716] ["Handle EstablishDisaggTask request done, resp_err=error_locked { msg: \"Key is locked (1 locks in region {8271})\" locked { primary_lock: \"t\\200\\000\\000\\000\\000\\000\\nx_r\\200\\000\\000\\000\\000+u\\014\" lock_version: 440858825740779643 key: \"t\\200\\000\\000\\000\\000\\000\\n|_r\\200\\000\\000\\000\\005w\\347\\014\" lock_ttl: 20043 txn_size: 9 lock_for_update_ts: 440858825753886812 min_commit_ts: 440858825766993992 } }"] [source="DisTaskId<MPP<query:<query_ts:1681742959048667887, local_query_id:839, server_id:2259244, start_ts:440858826251960386>,task_id:2>,executor=TableFullScan_28>"] [thread_id=92]
```

**Comment by JaySon-Huang** [comment] 2023-04-18 09:39
Should we sleep for `before_expired` when it is larger than 0? @breezewish 
https://github.com/pingcap/tiflash/blob/b9f1facbf59a79b850f906fbb1397d5930e366dd/dbms/src/Storages/StorageDisaggregatedRemote.cpp#L294-L297

the logic in client-c
https://github.com/tikv/client-c/blob/master/src/coprocessor/Client.cc#L535-L544

**Comment by JaySon-Huang** [comment] 2023-04-19 05:50
There were a total of 3 regions encountered with locks when the query first started. Even after the `before_expired` was down to 0 and 2 seconds had passed, 1 region still encountered a lock error. The `primary_lock` and `lock_version` information for all 3 locks were the same. In the end, only 1 lock remained unresolved out of the 3 regions.

It is inferred that the request failed due to slow synchronization in `tiflash`.

**Comment by JaySon-Huang** [comment] 2024-04-29 06:11
This issue is caused by "write stall" happens. It is not reproduced in recent tests, will reopen it if we happen to it again.

**Closed by JaySon-Huang** 2024-04-29 06:11 UTC
Labels: type/bug, severity/major, feature/developing, component/storage, affects-7.5, affects-8.1
