### ISSUE TITLE
TiFlash crash when scale out and run query

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#6646] opened 2023-01-17 04:10 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Scale out 10 TiFlash nodes and run TPCH queries at the same time.

### 2. What did you expect to see? (Required)
Don't crash.
### 3. What did you see instead (Required)
Some TiFlash nodes crashed.

[2023/01/16 22:13:09.443 +00:00] [ERROR] [BaseDaemon.cpp:377] [########################################] [source=BaseDaemon] [thread_id=1025]
[2023/01/16 22:13:09.443 +00:00] [ERROR] [BaseDaemon.cpp:378] ["(from thread 1024) Received signal Segmentation fault(11)."] [source=BaseDaemon] [thread_id=1025]
[2023/01/16 22:13:09.443 +00:00] [ERROR] [BaseDaemon.cpp:408] ["Address: 0x8"] [source=BaseDaemon] [thread_id=1025]
[2023/01/16 22:13:09.443 +00:00] [ERROR] [BaseDaemon.cpp:414] ["Access: read."] [source=BaseDaemon] [thread_id=1025]
[2023/01/16 22:13:09.443 +00:00] [ERROR] [BaseDaemon.cpp:423] ["Address not mapped to object."] [source=BaseDaemon] [thread_id=1025]

### 4. What is your TiFlash version? (Required)
v6.5.0 41c08dbe20901f6cfd28ce642b39ce53f35ef48a

**Comment by hehechen** [comment] 2023-01-17 04:24
[crash_tiflash_log_14.tar.gz](https://github.com/pingcap/tiflash/files/10431167/crash_tiflash_log_14.tar.gz)

**Comment by JaySon-Huang** [comment] 2023-01-17 10:42
Weirdly, there is no stack frame output to the log file...

**Comment by CalvinNeo** [comment] 2023-01-17 11:02
It is quite strange that there are no logs for what thread_1024 and thread_1025 is doing before thread_1024 is crashed.

**Comment by hehechen** [comment] 2023-01-18 06:44
I think it's better to write thread_name here.
https://github.com/pingcap/tiflash/blob/a17c0bb2cd8c47e4ef48b881548dafd234f5ed42/libs/libdaemon/src/BaseDaemon.cpp#L229

**Comment by hehechen** [comment] 2023-01-18 08:51
> I think it's better to write thread_name here.
> 
> https://github.com/pingcap/tiflash/blob/a17c0bb2cd8c47e4ef48b881548dafd234f5ed42/libs/libdaemon/src/BaseDaemon.cpp#L229

[`pthread_getname_np` is not asnyc-safe ](https://landonf.org/2013/01/19)so we can't use it in signal handler.

**Comment by JaySon-Huang** [comment] 2023-01-19 03:32
Seems the crash is caused by error happens when tracing the stack by libunwind
```
> 5-85 /data1/jaysonhuang/qa/flash_debug
>  LD_LIBRARY_PATH=. gdb  ./tiflash ./core.1
GNU gdb (GDB) 8.2
...
Reading symbols from ./tiflash...done.
BFD: warning: /data1/jaysonhuang/qa/flash_debug/./core.1 is truncated: expected core file size >= 359614476288, found: 1075888128

warning: core file may not match specified executable file.
...
Core was generated by `/tiflash/tiflash server --config-file /data0/config.toml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  access_mem (as=<optimized out>, addr=8, val=0x7fe902a408c8, write=<optimized out>, arg=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/libunwind/src/x86_64/Ginit.c:330
330 /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/libunwind/src/x86_64/Ginit.c: No such file or directory.
[Current thread is 1 (LWP 7)]
(gdb) bt
#0  access_mem (as=<optimized out>, addr=8, val=0x7fe902a408c8, write=<optimized out>, arg=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/libunwind/src/x86_64/Ginit.c:330
Backtrace stopped: Cannot access memory at address 0x7fe902a405f8
(gdb) info threads
  Id   Target Id         Frame
* 1    LWP 7             access_mem (as=<optimized out>, addr=8, val=0x7fe902a408c8, write=<optimized out>, arg=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/libunwind/src/x86_64/Ginit.c:330
  2    LWP 25            0x00007fe903b40c89 in ?? ()
  3    LWP 29            0x00007fe903b40c89 in ?? ()
  4    LWP 28            0x00007fe908607f00 in ?? ()
  5    LWP 37            0x00007fe904745de2 in ?? ()
  6    LWP 22            0x00007fe903b46f43 in ?? ()
  7    LWP 61            0x00007fe904745de2 in ?? ()
  8    LWP 160           0x0000000006f727a0 in LZ4_decompress_generic (src=<optimized out>, dst=<optimized out>, srcSize=<optimized out>, outputSize=<optimized out>, partialDecoding=decode_full_block,
    dict=noDict, lowPrefix=<optimized out>, dictStart=0x0, dictSize=0) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/lz4/lib/lz4.c:2060
  9    LWP 156           LZ4_decompress_generic (src=<optimized out>, dst=<optimized out>, srcSize=<optimized out>, outputSize=<optimized out>, partialDecoding=decode_full_block, dict=noDict,
    lowPrefix=<optimized out>, dictStart=0x0, dictSize=0) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/contrib/lz4/lib/lz4.c:2000
```

**Comment by hehechen** [comment] 2023-01-19 15:08
May it caused by continuous profiling?

**Comment by hehechen** [comment] 2023-01-30 07:09
Don't reproduce after disabling continuous profiling.

**Comment by yongman** [comment] 2023-03-17 17:26
Any updates?

**Comment by flowbehappy** [comment] 2023-04-10 06:08
Close this issue because cannot reproduction.

**Comment by JaySon-Huang** [comment] 2024-04-01 02:51
closed as can not reproduced for a long time

**Closed by JaySon-Huang** 2024-04-01 02:51 UTC
Labels: type/bug, severity/moderate, may-affects-4.0, may-affects-5.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-6.0, component/storage, may-affects-6.1, may-affects-6.2, may-affects-6.3, may-affects-6.4, affects-6.5, affects-6.6, affects-7.0
