### ISSUE TITLE
 Cannot convert NULL value to non-Nullable type

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tiflash#4556] opened 2022-04-01 06:44 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
mysql -uroot -h 172.16.4.99 -P 41324 -D agg_decimal_subquery700

```
SELECT ( ( table1 . `col_decimal_30_10_not_null_key` ) * ( table1 . `col_decimal_30_10_not_null_key` ) ) AS field1 ,  table1 . `col_decimal_20_20_not_null_key` = ALL ( SELECT   SUBQUERY1_t1 . `col_decimal_unsigned_not_null_key` AS SUBQUERY1_field1 FROM ( BB AS SUBQUERY1_t1 INNER JOIN ( C AS SUBQUERY1_t2 RIGHT OUTER JOIN BB AS SUBQUERY1_t3 ON (SUBQUERY1_t3 . `col_int_key` = SUBQUERY1_t2 . `col_decimal_30_10_unsigned_not_null_key`  ) ) ON (SUBQUERY1_t3 . `col_tinyint_unsigned` = SUBQUERY1_t2 . `col_int_key`  ) ) WHERE SUBQUERY1_t3 . `col_bigint_unsigned` <= -5   ) AS field2 , count( table1 . `col_int_not_null` ) AS field3 FROM ( D AS table1 INNER JOIN ( ( D AS table2 RIGHT OUTER JOIN (  SELECT   SUBQUERY2_t1 . * FROM ( D AS SUBQUERY2_t1 STRAIGHT_JOIN ( AA AS SUBQUERY2_t2 STRAIGHT_JOIN C AS SUBQUERY2_t3 ON (SUBQUERY2_t3 . `col_int_unsigned` = SUBQUERY2_t2 . `col_decimal_65_key`  ) ) ON (SUBQUERY2_t3 . `col_decimal_20_20_unsigned_not_null` = SUBQUERY2_t2 . `col_decimal_20_20_key`  ) ) WHERE SUBQUERY2_t1 . `col_bigint_not_null_key` = 9 ) AS table3 ON (table3 . `col_decimal_65_not_null`
= table2 . `col_int_key`  ) ) ) ON (table3 . `col_int_unsigned_key` = table2 . `col_decimal_65_key`  ) ) WHERE (  EXISTS ( SELECT   SUBQUERY3_t1 . `col_decimal_20_20` AS SUBQUERY3_field1 FROM ( C AS SUBQUERY3_t1 INNER JOIN CC AS SUBQUERY3_t2 ON (SUBQUERY3_t2 . `col_tinyint_unsigned_key` = SUBQUERY3_t1 . `col_decimal_65_10_key`  ) ) WHERE SUBQUERY3_t2 . `col_decimal_65` <= table3 . `col_decimal_30_10_unsigned_not_null_key` AND SUBQUERY3_t1 . `col_int_not_null` <> table2 . `col_decimal_65_unsigned` ) ) AND table1 . `col_decimal_30_10_key`  IN (84)  GROUP BY field1, field2  ;
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Exchange receiver meet error : DB::Exception: Cannot convert NULL value to non-Nullable type
```

### 4. What is your TiFlash version? (Required)
nightly of yesterday

**Comment by fzhedu** [comment] 2022-04-01 06:47
SELECT table1 . `col_int_unsigned_key` AS field1 , table1 . `col_decimal_30_key` AS field2 FROM ( BB AS table1 LEFT OUTER JOIN ( ( D AS table2 INNER JOIN B AS table3 ON (table3 . `col_decimal_not_null` = table2 . `col_decimal_65_10_key`  ) ) ) ON (table3 . `col_decimal_key` = table2 . `col_decimal_30_10_unsigned_not_null`  ) ) WHERE (  table1 . `col_decimal_20_20_not_null_key` = ALL ( SELECT   SUBQUERY1_t1 . `col_decimal_65_not_null_key` AS SUBQUERY1_field1 FROM AA AS SUBQUERY1_t1 WHERE SUBQUERY1_t1 . `col_tinyint_unsigned_key` >= table2 . `col_decimal_20_20_not_null` OR SUBQUERY1_t1 . `col_decimal_unsigned_key` <> table1 . `col_decimal_20_20_unsigned_not_null` ) ) OR table1 . `col_decimal_65_key` = table2 . `col_decimal_20_20_key` OR ( table1 . `col_bigint_unsigned_not_null` != table2 . `col_decimal_30_10_unsigned` AND  table1 . `col_decimal_20_20_unsigned_not_null_key`  IN ( SELECT 4.00 UNION  SELECT 4.00 ) )  GROUP BY field1, field2  ;

**Comment by fzhedu** [comment] 2022-04-01 06:52
SELECT  table1 . `col_decimal_30_10_not_null` >= ANY ( SELECT 84 UNION  SELECT -8.16 ) AS field1 ,  table1 . `col_decimal_65_unsigned_not_null_key` <= SOME ( SELECT 7 UNION  SELECT -5 ) AS field2 FROM ( BB AS table1 INNER JOI
N DD AS table2 ON (table2 . `col_decimal_key` = table1 . `col_decimal_65_unsigned_key`  ) ) WHERE (  table2 . `col_decimal_20_20_unsigned`  IN ( SELECT   SUBQUERY3_t2 . `col_tinyint_unsigned_not_null_key` AS SUBQUERY3_field1 FROM ( D AS SUBQUERY3_t1 RIGHT  JOIN CC AS SUBQUERY3_t2 ON (SUBQUERY3_t2 . `col_bigint_unsigned_not_null_key` = SUBQUERY3_t1 . `col_decimal_65_10_key`  ) ) WHERE  SUBQUERY3_t2 . `col_int` = ALL ( SELECT   CHILD_SUBQUERY1_t1 . `col_decimal_65_not_null` AS CHILD_SUBQUERY3_field1 FROM AA AS CHILD_SUBQUERY1_t1 WHERE CHILD_SUBQUERY1_t1 . `col_decimal_20_20` < SUBQUERY3_t2 . `col_decimal_30_10_not_null_key` )   ) ) OR ( table1 . `pk` = table2 . `col_decimal_key` AND table1 . `pk` = 235 )  GROUP BY field1, field2  ;

**Comment by fzhedu** [comment] 2022-04-01 06:52
SELECT max( table1 . `col_decimal_20_20_unsigned_not_null_key` ) AS field1 FROM ( D AS table1 STRAIGHT_JOIN ( ( DD AS table2 RIGHT  JOIN DD AS table3 ON (table3 . `col_bigint_unsigned` = table2 . `col_decimal_key`  ) ) ) ON (
table3 . `col_decimal_65_10_key` = table2 . `col_decimal`  ) ) WHERE (  table1 . `col_int_not_null` = ALL ( SELECT   SUBQUERY1_t1 . `col_decimal_30_10_unsigned_not_null` AS SUBQUERY1_field1 FROM ( B AS SUBQUERY1_t1 STRAIGHT_JOIN ( D AS SUBQUERY1_t2 STRAIGHT_JOIN D AS SUBQUERY1_t3 ON (SUBQUERY1_t3 . `col_decimal_not_null_key` = SUBQUERY1_t2 . `col_decimal_65_10_key`  ) ) ON (SUBQUERY1_t3 . `col_int_key` = SUBQUERY1_t2 . `col_int`  ) ) WHERE SUBQUERY1_t1 . `col_tinyint` < table2 . `col_decimal_65_unsigned_not_null_key` AND SUBQUERY1_t3 . `col_decimal_20_20_unsigned_not_null` != table3 . `col_int_unsigned` ) ) AND ( table1 . `col_decimal_65_key` = 129 OR table1 . `col_decimal_key` = table1 . `col_decimal_30_10_key` )   ;

**Comment by fzhedu** [comment] 2022-04-01 06:53
SELECT MAX(  table1 . `col_int_unsigned_key` ) AS field1 , ( ( table2 . `col_decimal_20_20_not_null_key` ) + ( table1 . `col_decimal_20_20_not_null_key` ) ) AS field2 FROM ( DD AS table1 STRAIGHT_JOIN C AS table2 ON (table2 . `col_decimal_65_10_key` = table1 . `col_decimal_65_10_unsigned`  ) ) WHERE (  table2 . `col_tinyint_unsigned_not_null_key` = ALL ( SELECT   SUBQUERY1_t1 . `col_decimal_20_20_unsigned_not_null_key` AS SUBQUERY1_field1 FROM ( CC AS SUBQUERY1_t1 STRAIGHT_JOIN AA AS SUBQUERY1_t2 ON (SUBQUERY1_t2 . `col_decimal_65_10_unsigned_not_null` = SUBQUERY1_t1 . `col_decimal_key`  ) ) WHERE SUBQUERY1_t1 . `col_decimal_65_unsigned_not_null_key` = table2 . `col_bigint` ) ) AND ( table1 . `col_decimal_20_20_key` = table1 . `col_decimal_30_10_key` OR table1 . `pk` = table1 . `col_decimal_30_10_key` )  GROUP BY field2  ;

**Comment by fzhedu** [comment] 2022-04-01 06:57
SELECT table2 . `col_bigint_not_null` AS field1 , table2 . `col_decimal_unsigned_key` AS field2 , table1 . `col_tinyint_key` AS field3 , MAX(  table1 . `col_decimal_65_10_unsigned` ) AS field4 ,  ( 4.00, 85 )  IN ( SELECT   SUBQUERY1_t1 . `col_bigint_not_null` AS SUBQUERY1_field1 , min( SUBQUERY1_t1 . `col_decimal_30_10_unsigned` ) AS SUBQUERY1_field2 FROM ( A AS SUBQUERY1_t1 INNER JOIN ( D AS SUBQUERY1_t2 STRAIGHT_JOIN DD AS SUBQUERY1_t3 ON (SUBQUERY1_t3 . `col_decimal_key` = SUBQUERY1_t2 . `col_tinyint_unsigned_not_null_key`  ) ) ON (SUBQUERY1_t3 . `col_decimal_not_null_key` = SUBQUERY1_t2 . `col_decimal_30_10_key`  ) ) WHERE  SUBQUERY1_t1 . `col_decimal_20_20_unsigned_key` = ALL ( SELECT   CHILD_SUBQUERY1_t1 . `col_decimal_65_10_not_null` AS CHILD_SUBQUERY1_field1 FROM AA AS CHILD_SUBQUERY1_t1    ) GROUP BY SUBQUERY1_field1  ) AS field5 FROM ( (  SELECT   SUBQUERY2_t2 . * FROM ( B AS SUBQUERY2_t1 INNER JOIN B AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `col_decimal_30_10_not_null` = SUBQUERY2_t1 . `pk`  ) ) WHERE ( SUBQUERY2_t2 . `col_tinyint_not_null_key` != 3 AND   EXISTS ( SELECT   CHILD_SUBQUERY2_t1 . `col_decimal_65_10_not_null_key` AS CHILD_SUBQUERY2_field1 FROM ( DD AS CHILD_SUBQUERY2_t1 STRAIGHT_JOIN A AS CHILD_SUBQUERY2_t2 ON (CHILD_SUBQUERY2_t2 . `col_int_unsigned_not_null_key` = CHILD_SUBQUERY2_t1 . `col_decimal_20_20_key` ) ) WHERE CHILD_SUBQUERY2_t2 . `col_int_unsigned` >= SUBQUERY2_t1 . `col_bigint_unsigned_not_null` ) ) ) AS table1 LEFT  JOIN BB AS table2 ON (table2 . `col_decimal_20_20_key` = table1 . `col_bigint_unsigned_not_null_key`  ) ) WHERE (  table1 . `col_decimal_65_not_null_key`  IN ( SELECT 7 FROM DUAL ) ) AND ( table1 . `pk` = 150 OR table1 . `pk` = 105 )  GROUP BY field1, field2, field3, field5  ;

**Comment by fzhedu** [comment] 2022-04-01 07:02
SELECT  table1 . `col_decimal_65_10_unsigned_not_null_key` <= ANY ( SELECT 1 UNION DISTINCT SELECT 4.00 ) AS field1 FROM ( BB AS table1 LEFT OUTER JOIN ( ( CC AS table2 LEFT OUTER JOIN C AS table3 ON (table3 . `col_decimal_65_key` = table2 . `col_decimal_20_20_unsigned`  ) ) ) ON (table3 . `col_bigint_unsigned_not_null_key` = table2 . `col_int_key`  ) ) WHERE (  table2 . `col_decimal_unsigned_not_null`  IN ( SELECT   SUBQUERY2_t1 . `col_decimal_not_null_key` AS SUBQUERY2_field1 FROM ( B AS SUBQUERY2_t1 STRAIGHT_JOIN CC AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `col_decimal_not_null_key` = SUBQUERY2_t1 . `col_decimal_20_20_key`  ) ) WHERE (  SUBQUERY2_t1 . `col_decimal_30_10` = ALL ( SELECT   CHILD_SUBQUERY1_t1 . `col_decimal_65_10_not_null_key` AS CHILD_SUBQUERY1_field1 FROM ( B AS CHILD_SUBQUERY1_t1 STRAIGHT_JOIN AA AS CHILD_SUBQUERY1_t2 ON (CHILD_SUBQUERY1_t2 . `col_bigint` = CHILD_SUBQUERY1_t1 . `col_decimal_65_key` ) )    ) OR SUBQUERY2_t2 . `col_decimal_65_10_unsigned_key` > 9 )   ) ) AND table1 . `col_decimal_30_10` IS  NULL  GROUP BY field1  ;

**Comment by fzhedu** [comment] 2022-04-01 07:06
SELECT  ( table1 . `col_decimal_30_10_not_null` , table1 . `col_decimal_65_unsigned` )  IN ( SELECT   SUBQUERY1_t1 . `col_decimal_30_10_not_null_key` AS SUBQUERY1_field1 , SUBQUERY1_t1 . `col_int_unsigned_not_null` AS SUBQU
ERY1_field2 FROM ( D AS SUBQUERY1_t1 LEFT OUTER JOIN D AS SUBQUERY1_t2 ON (SUBQUERY1_t2 . `col_tinyint_unsigned_key` = SUBQUERY1_t1 . `col_decimal_30_10_key`  ) ) WHERE SUBQUERY1_t2 . `col_decimal_20_20_unsigned` >= SUBQUERY1_t1 . `col_tinyint_unsigned_key`   ) AS field1 , table1 . `col_decimal_20_20_unsigned` AS field2 , SUM(  table2 . `col_decimal_20_20_key` ) AS field3 ,  table1 . `col_decimal_not_null_key` = ALL ( SELECT   SUBQUERY2_t1 . `col_int_not_null` AS SUBQUERY2_field1 FROM ( AA AS SUBQUERY2_t1 STRAIGHT_JOIN DD AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `col_int_unsigned_key` = SUBQUERY2_t1 . `col_decimal_65_key`  ) )    ) AS field4 FROM ( D AS table1 INNER JOIN ( ( DD AS table2 STRAIGHT_JOIN C AS table3 ON (table3 . `col_int_unsigned_not_null` = table2 . `col_decimal_65_10_key`  ) ) ) ON (table3 . `col_decimal_65_10_key` = table2 . `col_tinyint_unsigned_key`  ) ) WHERE (   EXISTS ( SELECT   SUBQUERY3_t1 . `col_tinyint_not_null_key` AS SUBQUERY3_field1 FROM ( DD AS SUBQUERY3_t1 INNER JOIN ( C AS SUBQUERY3_t2 INNER JOIN AA AS SUBQUERY3_t3 ON (SUBQUERY3_t3 . `col_decimal_20_20_key` = SUBQUERY3_t2 . `col_int_unsigned_key`  ) ) ON (SUBQUERY3_t3 . `col_decimal_30_10_unsigned` = SUBQUERY3_t2 . `col_decimal_30_10_key`  ) ) WHERE  SUBQUERY3_t1 . `col_tinyint_not_null_key`  IN ( SELECT   CHILD_SUBQUERY1_t1 . `col_decimal_unsigned` AS CHILD_SUBQUERY3_field1 FROM A AS CHILD_SUBQUERY1_t1 WHERE CHILD_SUBQUERY1_t1 . `col_bigint_not_null` != SUBQUERY3_t1 . `col_decimal_65_10_not_null_key` OR CHILD_SUBQUERY1_t1 . `col_decimal_30_10_unsigned_key` <> CHILD_SUBQUERY1_t1 . `col_bigint_not_null_key` )   ) ) OR ( table1 . `col_int_key`  IN (190, 143) OR table1 . `col_int_key` > 64 AND table1 . `col_int_key` < ( 64 + 162 ) )  GROUP BY field1, field2, field4  ;

**Comment by fzhedu** [comment] 2022-04-01 07:10
SELECT table1 . `col_int_unsigned_not_null_key` AS field1 ,  table1 . `col_decimal_20_20_not_null_key` = ALL ( SELECT   SUBQUERY1_t2 . `col_decimal_65_unsigned_not_null_key` AS SUBQUERY1_field1 FROM ( AA AS SUBQUERY1_t1 STR
AIGHT_JOIN BB AS SUBQUERY1_t2 ON (SUBQUERY1_t2 . `col_decimal_30_10_key` = SUBQUERY1_t1 . `col_tinyint`  ) )    ) AS field2 FROM ( D AS table1 RIGHT OUTER JOIN CC AS table2 ON (table2 . `col_decimal_20_20_unsigned` = table1 . `col_decimal_20_20_key`  ) ) WHERE (  table1 . `col_decimal_20_20_unsigned_not_null_key`  IN ( SELECT 3 UNION  SELECT 4.00 ) ) AND table1 . `col_int_key` = 42  GROUP BY field1, field2  ;

**Comment by fzhedu** [comment] 2022-04-01 07:18
SELECT table2 . `col_decimal_20_20_not_null_key` AS field1 FROM ( DD AS table1 LEFT OUTER JOIN BB AS table2 ON (table2 . `col_int` = table1 . `col_int_key`  ) ) WHERE (  table2 . `col_decimal_65_unsigned_key` = ALL ( SELECT   SUBQUERY1_t1 . `col_bigint_not_null_key` AS SUBQUERY1_field1 FROM ( D AS SUBQUERY1_t1 STRAIGHT_JOIN ( BB AS SUBQUERY1_t2 STRAIGHT_JOIN CC AS SUBQUERY1_t3 ON (SUBQUERY1_t3 . `col_bigint_unsigned_key` = SUBQUERY1_t2 . `col_decimal_65_key`  ) ) ON (SUBQUERY1_t3 . `col_bigint_unsigned_not_null_key` = SUBQUERY1_t2 . `col_decimal_65_key`  ) ) WHERE SUBQUERY1_t1 . `col_decimal_unsigned_not_null_key` = table1 . `col_decimal_65` AND SUBQUERY1_t1 . `col_decimal_20_20` < table1 . `col_bigint_unsigned_not_null_key` ) ) AND ( table1 . `col_int_key` = 116 AND table1 . `col_decimal_65_10_key` = table1 . `col_decimal_65_key` ) OR  EXISTS ( SELECT   SUBQUERY2_t1 . `col_decimal_65_10_unsigned` AS SUBQUERY2_field1 FROM ( B AS SUBQUERY2_t1 STRAIGHT_JOIN BB AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `pk` = SUBQUERY2_t1 . `col_decimal_65_10_not_null`  ) ) WHERE SUBQUERY2_t2 . `col_decimal` >= table2 . `col_int_not_null` OR SUBQUERY2_t2 . `col_decimal_20_20_unsigned_not_null` <= table2 . `col_decimal_65_unsigned_not_null` )  GROUP BY field1  ;

**Comment by fzhedu** [comment] 2022-04-01 07:21
SELECT ( ( table1 . `col_decimal_30_10_unsigned_not_null_key` ) * ( table1 . `col_decimal_30_10_unsigned` ) ) AS field1 , MAX(  table1 . `col_decimal_30_10_unsigned_key` ) AS field2 FROM ( (  SELECT   SUBQUERY1_t1 . * FROM ( C AS SUBQUERY1_t1 RIGHT OUTER JOIN C AS SUBQUERY1_t2 ON (SUBQUERY1_t2 . `col_decimal_65_key` = SUBQUERY1_t1 . `col_decimal_unsigned_not_null`  ) ) WHERE (  SUBQUERY1_t1 . `col_decimal_65_unsigned` = ALL ( SELECT   CHILD_SUBQUERY1_t1 . `col_decimal_65_not_null` AS CHILD_SUBQUERY1_field1 FROM C AS CHILD_SUBQUERY1_t1 WHERE CHILD_SUBQUERY1_t1 . `col_decimal_not_null` <= SUBQUERY1_t2 . `col_decimal_65_10_not_null` ) OR SUBQUERY1_t1 . `col_decimal_65_unsigned_not_null` != 3 ) ) AS table1 INNER JOIN ( ( CC AS table2 RIGHT OUTER JOIN DD AS table3 ON (table3 . `col_tinyint_unsigned_not_null_key` = table2 . `col_decimal_key`  ) ) ) ON (table3 . `pk` = table2 . `col_decimal_unsigned`  ) ) WHERE (  table1 . `col_decimal_65_10` != ( SELECT   count( SUBQUERY2_t1 . `col_int_unsigned_not_null_key` ) AS SUBQUERY2_field1 FROM ( DD AS SUBQUERY2_t1 STRAIGHT_JOIN B AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `col_decimal_65_10_key` = SUBQUERY2_t1 . `col_bigint_unsigned`  ) )  ) ) OR table1 . `col_int_key` = 93 AND table1 . `col_decimal_unsigned_not_null_key` = table1 . `col_decimal_30_10_unsigned_not_null_key`  GROUP BY field1  ;

**Comment by fzhedu** [comment] 2022-04-26 10:33
all correlated subquery has errors.
```
SELECT table2 . * FROM C AS table2 WHERE( table2 . `col_tinyint_unsigned_not_null_key` = all(SELECT SUBQUERY1_t1 . `col_decimal_20_20_unsigned_not_null_key` AS SUBQUERY1_field1 FROM CC AS SUBQUERY1_t1 WHERE SUBQUERY1_t1 . `col_decimal_65_unsigned_not_null_key` = table2 . `col_bigint`) );
```

**Comment by fixdb** [comment] 2022-05-10 06:09
Smaller repo:
```sql
create table foo(a int, b int);
insert into foo values(0, NULL);
alter table foo set tiflash replica 1;


create table bar(a double not null, b decimal(65,0)  not null);
insert into bar values(0, 0);
alter table bar set tiflash  replica 1;

select * from foo where a=all(select a from bar where bar.b=foo.b);
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Cannot convert NULL value to non-Nullable type

select * from foo where a=all(select 1 from bar where bar.b=foo.b);
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Cannot convert NULL value to non-Nullable type
```

But in Tikv, it is getting expected result, same with MySQL:
```sql
mysql> set tidb_allow_mpp=0;
Query OK, 0 rows affected (0.19 sec)

mysql> select * from foo where a=all(select a from bar where bar.b=foo.b);
+------+------+
| a    | b    |
+------+------+
|    0 | NULL |
+------+------+
1 row in set (0.19 sec)
```

**Comment by LittleFall** [comment] 2022-09-20 07:18
reproduce in 6.1, can't reproduce in 6.2
```sql
mysql>  select * from foo where a=all(select a from bar where bar.b=foo.b);
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Cannot convert NULL value to non-Nullable type
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:09:34
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

```sql
MySQL [test]> select * from foo where a=all(select a from bar where bar.b=foo.b);
+------+------+
| a    | b    |
+------+------+
|    0 | NULL |
+------+------+
1 row in set (0.01 sec)
MySQL [test]> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.2.0
Edition: Community
Git Commit Hash: daf2b17cdfe30c02ce282361009fb5bdb05f2b0e
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-08-22 13:47:05
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by LittleFall** [comment] 2022-09-20 07:36
hi @fixdb, have you fixed this issue in https://github.com/pingcap/tidb/issues/34584?
can we close this issue and https://github.com/pingcap/tidb/pull/34582?

**Comment by fixdb** [comment] 2022-09-20 19:05
@LittleFall Yes, it has beed fixed, we can close the issue.

**Closed** 2022-09-21 05:41 UTC
Labels: type/bug, severity/major, plan, may-affects-4.0, may-affects-5.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-6.0, randgen, component/compute, affects-6.1, affects-6.2, affects-6.3
