### ISSUE TITLE
the same primary row return multiple rows with different versions in fast scan mode

### ISSUE THREAD

**Issue by bestwoody** [pingcap/tiflash#7634] opened 2023-06-09 08:53 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**Comment by SeaRise** [comment] 2023-06-09 09:28
Please avoid adding non-public information such as `ONCALL-6266` and add some relevant information

**Comment by hongyunyan** [comment] 2023-06-12 02:17
In fast scan mode, it matches expectation that the result contains the multi-version data.

**Comment by JaySon-Huang** [comment] 2023-06-15 08:16
Update the doc to describe more details about the behavior of FastScan https://github.com/pingcap/docs-cn/pull/14190

**Comment by windtalker** [comment] 2023-07-27 07:17
Close this issue since it is the expected behavior in fast mode.

**Closed by windtalker** 2023-07-27 07:17 UTC
Labels: type/bug, severity/major, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, component/storage, may-affects-6.1, may-affects-6.5, may-affects-7.1
