### ISSUE TITLE
TiFlash failed Region unavailable

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#8094] opened 2023-09-14 07:35 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![img_v2_6c1fde76-f518-4b56-a0e9-fc43b002e29g](https://github.com/pingcap/tiflash/assets/7677963/e7c159d0-f9b0-4fd7-80e9-708a9ffd88bb)
```
mysql> select count(*) from common_handle1;
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: Region unavailable, region_id=81590 wait_index=4121 applied_index=3218: (while doing learner read for table, logical table_id=272), e.what() = DB::TiFlashException,
```
tiflash2 store status is down but the process is up
```
"store": {
        "id": 324,
        "address": "[tc-tiflash-2.tc](http://tc-tiflash-2.tc/)-tiflash-peer.endless-htap-consistency2-tps-2460297-1-289.svc:3930",
        "labels": [
          {
            "key": "engine",
            "value": "tiflash"
          }
        ],
        "version": "v7.4.0-alpha",
        "peer_address": "[tc-tiflash-2.tc](http://tc-tiflash-2.tc/)-tiflash-peer.endless-htap-consistency2-tps-2460297-1-289.svc:20170",
        "status_address": "[tc-tiflash-2.tc](http://tc-tiflash-2.tc/)-tiflash-peer.endless-htap-consistency2-tps-2460297-1-289.svc:20292",
        "git_hash": "e09ec61358bfefce6dd42c32b289df1f739f3b1c",
        "start_timestamp": 1694594249,
        "deploy_path": "/tiflash",
        "last_heartbeat": 1694643148396835666,
        "state_name": "Down"
```
tiflash1
```
[root@tc-tiflash-1 data]# du -h -d 1
1.2G	./t_272
153G	./t_321
295G	./t_356
4.0K	./system
590G	./t_342
158G	./t_328
5.0G	./t_349
304M	./t_307
107G	./t_314
41G	./t_293
21G	./t_279
155G	./t_335
44G	./t_286
337M	./t_300
1.6T	.
```
### 4. What is your TiFlash version? (Required)
TiFlash
Release Version: v7.4.0-alpha
Edition:         Community
Git Commit Hash: e09ec61358bfefce6dd42c32b289df1f739f3b1c
Git Branch:      heads/refs/tags/v7.4.0-alpha
UTC Build Time:  2023-09-13 06:43:35
Enable Features: jemalloc sm4(GmSSL) avx2 avx512 unwind thinlto
Profile:         RELWITHDEBINFO

Raft Proxy
Git Commit Hash:   cb91c8cc5a6c2d525ddee5251ecc11e16a1fd272
Git Commit Branch: HEAD
UTC Build Time:    2023-09-13 06:50:53
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Storage Engine:    tiflash
Prometheus Prefix: tiflash_proxy_
Profile:           release
Enable Features:    portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure

**Comment by JaySon-Huang** [comment] 2023-09-18 03:18
The issue is caused by there are unreleased MPP tasks. So TiFlash can not run GC on the outdated data.
![b0702e6c-4d33-4916-808b-9259a713b3da](https://github.com/pingcap/tiflash/assets/4865550/40e5ab22-cafb-4b9b-bf09-224dee471722)

The MPP Task leak issue is fixed by https://github.com/pingcap/tiflash/pull/8101
And another issue that Grafana can not show the max snapshot lifetime is fixed by https://github.com/pingcap/tiflash/pull/8102

**Closed by JaySon-Huang** 2023-09-18 03:18 UTC
Labels: type/bug
